name: Tag Version

on:
  schedule:
    - cron: '0 4 * * 6'
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  tag-version:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/luzifer-docker/action-env:2026.31.2@sha256:3ef7f24932aa2d18440c71e39ad714bfe06a7319f2753d5d6138afbe0a62f08b

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          show-progress: false

      - name: Log into registry
        run: skopeo login ghcr.io --username "${GITHUB_ACTOR}" --password-stdin <<<"${GITHUB_TOKEN}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag version
        run: bash ci/tag-version.sh
